FROM node:16-alpine

WORKDIR /app
COPY . .

ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL

ARG NEXT_PUBLIC_MATOMO_SITE_ID
ENV NEXT_PUBLIC_MATOMO_SITE_ID=$NEXT_PUBLIC_MATOMO_SITE_ID

ARG NEXT_PUBLIC_MATOMO_URL
ENV NEXT_PUBLIC_MATOMO_URL=$NEXT_PUBLIC_MATOMO_URL

ARG NEXT_PUBLIC_MATOMO_ENABLED
ENV NEXT_PUBLIC_MATOMO_ENABLED=$NEXT_PUBLIC_MATOMO_ENABLED

ARG NEXT_PUBLIC_TEST_NUMBER_ENABLED
ENV NEXT_PUBLIC_TEST_NUMBER_ENABLED=$NEXT_PUBLIC_TEST_NUMBER_ENABLED

ARG NEXT_PUBLIC_PASTEK_CHAT_ID
ENV NEXT_PUBLIC_PASTEK_CHAT_ID=$NEXT_PUBLIC_PASTEK_CHAT_ID

ARG NEXT_PUBLIC_LANDING_PAGE_BLUES_RESOURCES
ENV NEXT_PUBLIC_LANDING_PAGE_BLUES_RESOURCES=$NEXT_PUBLIC_LANDING_PAGE_BLUES_RESOURCES

RUN yarn --production --frozen-lockfile --prefer-offline && yarn cache clean
RUN yarn build

USER 1000

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV NEXT_TELEMETRY_DEBUG=0

CMD ["yarn", "start"]
